<?php
    /**
     * Created by PhpStorm.
     * User: skhanker
     * Date: 01/05/2015
     * Time: 11:50 AM
     */
    namespace OpenLibrary\Repositories\ISO\Series639\Revision1;

    class ISO_639_1
    {

        const Afara            = "aa";
        const Abkhazian        = "ab";
        const Avestan          = "ae";
        const Afrikaans        = "af";
        const Akan             = "ak";
        const Amharic          = "am";
        const Aragonese        = "an";
        const Arabic           = "ar";
        const Assamese         = "as";
        const Avaric           = "av";
        const Aymara           = "ay";
        const Azerbaijani      = "az";
        const Bashkir          = "ba";
        const Belarusian       = "be";
        const Bulgarian        = "bg";
        const Bihari           = "bh";
        const Bislama          = "bi";
        const Bambara          = "bm";
        const Bengali          = "bn";
        const Tibetan          = "bo";
        const Breton           = "br";
        const Bosnian          = "bs";
        const Catalan          = "ca";
        const Chechen          = "ce";
        const Chamorro         = "ch";
        const Corsican         = "co";
        const Cree             = "cr";
        const Czech            = "cs";
        const ChurchSlavic     = "cu";
        const Chuvash          = "cv";
        const Welsh            = "cy";
        const Danish           = "da";
        const German           = "de";
        const Divehi           = "dv";
        const Dzongkha         = "dz";
        const Ewe              = "ee";
        const Greek            = "el";
        const English          = "en";
        const Esperanto        = "eo";
        const Spanish          = "es";
        const Estonian         = "et";
        const Basque           = "eu";
        const Persian          = "fa";
        const Fulah            = "ff";
        const Finnish          = "fi";
        const Fijian           = "fj";
        const Faroese          = "fo";
        const French           = "fr";
        const WesternFrisian   = "fy";
        const Irish            = "ga";
        const ScottishGaelic   = "gd";
        const Galician         = "gl";
        const Guarani          = "gn";
        const Gujarati         = "gu";
        const Manx             = "gv";
        const Hausa            = "ha";
        const Hebrew           = "he";
        const Hindi            = "hi";
        const HiriMotu         = "ho";
        const Croatian         = "hr";
        const Haitian          = "ht";
        const Hungarian        = "hu";
        const Armenian         = "hy";
        const Herero           = "hz";
        const Interlingua      = "ia";
        const Indonesian       = "id";
        const Interlingue      = "ie";
        const Igbo             = "ig";
        const SichuanYi        = "ii";
        const Inupiaq          = "ik";
        const Ido              = "io";
        const Icelandic        = "is";
        const Italian          = "it";
        const Inuktitut        = "iu";
        const Japanese         = "ja";
        const Javanese         = "jv";
        const Georgian         = "ka";
        const Kongo            = "kg";
        const Kikuyu           = "ki";
        const Kwanyama         = "kj";
        const Kazakh           = "kk";
        const Kalaallisut      = "kl";
        const Khmer            = "km";
        const Kannada          = "kn";
        const Korean           = "ko";
        const Kanuri           = "kr";
        const Kashmiri         = "ks";
        const Kurdish          = "ku";
        const Komi             = "kv";
        const Cornish          = "kw";
        const Kirghiz          = "ky";
        const Latin            = "la";
        const Luxembourgish    = "lb";
        const Ganda            = "lg";
        const Limburgish       = "li";
        const Lingala          = "ln";
        const Lao              = "lo";
        const Lithuanian       = "lt";
        const LubaKatanga      = "lu";
        const Latvian          = "lv";
        const Malagasy         = "mg";
        const Marshallese      = "mh";
        const Maori            = "mi";
        const Macedonian       = "mk";
        const Malayalam        = "ml";
        const Mongolian        = "mn";
        const Marathi          = "mr";
        const Malay            = "ms";
        const Maltese          = "mt";
        const Burmese          = "my";
        const Nauru            = "na";
        const NorwegianBokmal  = "nb";
        const NorthNdebele     = "nd";
        const Nepali           = "ne";
        const Ndonga           = "ng";
        const Dutch            = "nl";
        const NorwegianNynorsk = "nn";
        const Norwegian        = "no";
        const SouthNdebele     = "nr";
        const Navajo           = "nv";
        const Chichewa         = "ny";
        const Occitan          = "oc";
        const Ojibwa           = "oj";
        const Oromo            = "om";
        const Oriya            = "or";
        const Ossetian         = "os";
        const Panjabi          = "pa";
        const Pali             = "pi";
        const Polish           = "pl";
        const Pashto           = "ps";
        const Portuguese       = "pt";
        const Quechua          = "qu";
        const RaetoRomance     = "rm";
        const Kirundi          = "rn";
        const Romanian         = "ro";
        const Russian          = "ru";
        const Kinyarwanda      = "rw";
        const Sanskrit         = "sa";
        const Sardinian        = "sc";
        const Sindhi           = "sd";
        const NorthernSami     = "se";
        const Sango            = "sg";
        const Sinhala          = "si";
        const Slovak           = "sk";
        const Slovenian        = "sl";
        const Samoan           = "sm";
        const Shona            = "sn";
        const Somali           = "so";
        const Albanian         = "sq";
        const Serbian          = "sr";
        const Swati            = "ss";
        const SouthernSotho    = "st";
        const Sundanese        = "su";
        const Swedish          = "sv";
        const Swahili          = "sw";
        const Tamil            = "ta";
        const Telugu           = "te";
        const Tajik            = "tg";
        const Thai             = "th";
        const Tigrinya         = "ti";
        const Turkmen          = "tk";
        const Tagalog          = "tl";
        const Tswana           = "tn";
        const Tonga            = "to";
        const Turkish          = "tr";
        const Tsonga           = "ts";
        const Tatar            = "tt";
        const Twi              = "tw";
        const Tahitian         = "ty";
        const Uighur           = "ug";
        const Ukrainian        = "uk";
        const Urdu             = "ur";
        const Uzbek            = "uz";
        const Venda            = "ve";
        const Vietnamese       = "vi";
        const Volapuk          = "vo";
        const Walloon          = "wa";
        const Wolof            = "wo";
        const Xhosa            = "xh";
        const Yiddish          = "yi";
        const Yoruba           = "yo";
        const Zhuang           = "za";
        const Chinese          = "zh";
        const Zulu             = "zu";

        protected static $languageCodes = [
            "aa" => "Afar",
            "ab" => "Abkhazian",
            "ae" => "Avestan",
            "af" => "Afrikaans",
            "ak" => "Akan",
            "am" => "Amharic",
            "an" => "Aragonese",
            "ar" => "Arabic",
            "as" => "Assamese",
            "av" => "Avaric",
            "ay" => "Aymara",
            "az" => "Azerbaijani",
            "ba" => "Bashkir",
            "be" => "Belarusian",
            "bg" => "Bulgarian",
            "bh" => "Bihari",
            "bi" => "Bislama",
            "bm" => "Bambara",
            "bn" => "Bengali",
            "bo" => "Tibetan",
            "br" => "Breton",
            "bs" => "Bosnian",
            "ca" => "Catalan",
            "ce" => "Chechen",
            "ch" => "Chamorro",
            "co" => "Corsican",
            "cr" => "Cree",
            "cs" => "Czech",
            "cu" => "Church Slavic",
            "cv" => "Chuvash",
            "cy" => "Welsh",
            "da" => "Danish",
            "de" => "German",
            "dv" => "Divehi",
            "dz" => "Dzongkha",
            "ee" => "Ewe",
            "el" => "Greek",
            "en" => "English",
            "eo" => "Esperanto",
            "es" => "Spanish",
            "et" => "Estonian",
            "eu" => "Basque",
            "fa" => "Persian",
            "ff" => "Fulah",
            "fi" => "Finnish",
            "fj" => "Fijian",
            "fo" => "Faroese",
            "fr" => "French",
            "fy" => "Western Frisian",
            "ga" => "Irish",
            "gd" => "Scottish Gaelic",
            "gl" => "Galician",
            "gn" => "Guarani",
            "gu" => "Gujarati",
            "gv" => "Manx",
            "ha" => "Hausa",
            "he" => "Hebrew",
            "hi" => "Hindi",
            "ho" => "Hiri Motu",
            "hr" => "Croatian",
            "ht" => "Haitian",
            "hu" => "Hungarian",
            "hy" => "Armenian",
            "hz" => "Herero",
            "ia" => "Interlingua (International Auxiliary Language Association)",
            "id" => "Indonesian",
            "ie" => "Interlingue",
            "ig" => "Igbo",
            "ii" => "Sichuan Yi",
            "ik" => "Inupiaq",
            "io" => "Ido",
            "is" => "Icelandic",
            "it" => "Italian",
            "iu" => "Inuktitut",
            "ja" => "Japanese",
            "jv" => "Javanese",
            "ka" => "Georgian",
            "kg" => "Kongo",
            "ki" => "Kikuyu",
            "kj" => "Kwanyama",
            "kk" => "Kazakh",
            "kl" => "Kalaallisut",
            "km" => "Khmer",
            "kn" => "Kannada",
            "ko" => "Korean",
            "kr" => "Kanuri",
            "ks" => "Kashmiri",
            "ku" => "Kurdish",
            "kv" => "Komi",
            "kw" => "Cornish",
            "ky" => "Kirghiz",
            "la" => "Latin",
            "lb" => "Luxembourgish",
            "lg" => "Ganda",
            "li" => "Limburgish",
            "ln" => "Lingala",
            "lo" => "Lao",
            "lt" => "Lithuanian",
            "lu" => "Luba-Katanga",
            "lv" => "Latvian",
            "mg" => "Malagasy",
            "mh" => "Marshallese",
            "mi" => "Maori",
            "mk" => "Macedonian",
            "ml" => "Malayalam",
            "mn" => "Mongolian",
            "mr" => "Marathi",
            "ms" => "Malay",
            "mt" => "Maltese",
            "my" => "Burmese",
            "na" => "Nauru",
            "nb" => "Norwegian Bokmal",
            "nd" => "North Ndebele",
            "ne" => "Nepali",
            "ng" => "Ndonga",
            "nl" => "Dutch",
            "nn" => "Norwegian Nynorsk",
            "no" => "Norwegian",
            "nr" => "South Ndebele",
            "nv" => "Navajo",
            "ny" => "Chichewa",
            "oc" => "Occitan",
            "oj" => "Ojibwa",
            "om" => "Oromo",
            "or" => "Oriya",
            "os" => "Ossetian",
            "pa" => "Panjabi",
            "pi" => "Pali",
            "pl" => "Polish",
            "ps" => "Pashto",
            "pt" => "Portuguese",
            "qu" => "Quechua",
            "rm" => "Raeto-Romance",
            "rn" => "Kirundi",
            "ro" => "Romanian",
            "ru" => "Russian",
            "rw" => "Kinyarwanda",
            "sa" => "Sanskrit",
            "sc" => "Sardinian",
            "sd" => "Sindhi",
            "se" => "Northern Sami",
            "sg" => "Sango",
            "si" => "Sinhala",
            "sk" => "Slovak",
            "sl" => "Slovenian",
            "sm" => "Samoan",
            "sn" => "Shona",
            "so" => "Somali",
            "sq" => "Albanian",
            "sr" => "Serbian",
            "ss" => "Swati",
            "st" => "Southern Sotho",
            "su" => "Sundanese",
            "sv" => "Swedish",
            "sw" => "Swahili",
            "ta" => "Tamil",
            "te" => "Telugu",
            "tg" => "Tajik",
            "th" => "Thai",
            "ti" => "Tigrinya",
            "tk" => "Turkmen",
            "tl" => "Tagalog",
            "tn" => "Tswana",
            "to" => "Tonga",
            "tr" => "Turkish",
            "ts" => "Tsonga",
            "tt" => "Tatar",
            "tw" => "Twi",
            "ty" => "Tahitian",
            "ug" => "Uighur",
            "uk" => "Ukrainian",
            "ur" => "Urdu",
            "uz" => "Uzbek",
            "ve" => "Venda",
            "vi" => "Vietnamese",
            "vo" => "Volapuk",
            "wa" => "Walloon",
            "wo" => "Wolof",
            "xh" => "Xhosa",
            "yi" => "Yiddish",
            "yo" => "Yoruba",
            "za" => "Zhuang",
            "zh" => "Chinese",
            "zu" => "Zulu"
        ];

        public static function getLanguageCodes ()
        {
            $rc = new \ReflectionClass(__CLASS__);
            return $rc->getConstants ();
        }

        /* le older way - probs want to remove the below */

        public static function getLanguageLabelFromCode ($code)
        {
            if (isset(self::$languageCodes[$code])) {
                return self::$languageCodes[$code];
            }

            return "Language not found for code [$code]";
        }

        public static function getLanguageCodeFromLabel ($label)
        {
            $lc = array_flip (self::$languageCodes);
            if (isset($lc[$label])) {
                return $lc[$label];
            }

            return "Language not found for label [$label]";
        }
    }
